// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class Testnisluaj5Test {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void testnisluaj5() {
    driver.Navigate().GoToUrl("https://demo.nopcommerce.com/");
    driver.Manage().Window.Size = new System.Drawing.Size(1552, 840);
    Assert.That(driver.FindElement(By.CssSelector(".topic-block-title > h2")).Text, Is.EqualTo("Welcome to our store"));
    driver.FindElement(By.CssSelector(".topic-block-title > h2")).Click();
    driver.FindElement(By.CssSelector(".nivo-imageLink:nth-child(1)")).Click();
    driver.FindElement(By.CssSelector(".topic-block-title > h2")).Click();
    Assert.That(driver.FindElement(By.CssSelector(".topic-block-title > h2")).Text, Is.EqualTo("Welcome to our store"));
    driver.FindElement(By.CssSelector(".topic-block-title > h2")).Click();
    driver.FindElement(By.CssSelector(".nivo-imageLink:nth-child(2)")).Click();
    driver.FindElement(By.CssSelector(".topic-block-title > h2")).Click();
    Assert.That(driver.FindElement(By.CssSelector(".topic-block-title > h2")).Text, Is.EqualTo("Welcome to our store"));
    driver.Close();
  }
}
