// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class Testnisluaj1Test {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void testnisluaj1() {
    driver.Navigate().GoToUrl("https://demo.nopcommerce.com/");
    driver.Manage().Window.Size = new System.Drawing.Size(1552, 840);
    driver.FindElement(By.LinkText("Register")).Click();
    driver.FindElement(By.Id("FirstName")).Click();
    driver.FindElement(By.Id("FirstName")).SendKeys("test");
    driver.FindElement(By.Id("LastName")).Click();
    driver.FindElement(By.Id("LastName")).SendKeys("test");
    driver.FindElement(By.Id("Email")).Click();
    driver.FindElement(By.Id("Email")).SendKeys("test@mail.com");
    driver.FindElement(By.Id("Newsletter")).Click();
    driver.FindElement(By.Id("Password")).Click();
    driver.FindElement(By.Id("Password")).SendKeys("test123");
    driver.FindElement(By.Id("ConfirmPassword")).Click();
    driver.FindElement(By.Id("ConfirmPassword")).SendKeys("test123");
    driver.FindElement(By.Id("register-button")).Click();
    driver.FindElement(By.CssSelector(".result")).Click();
    Assert.That(driver.FindElement(By.CssSelector(".result")).Text, Is.EqualTo("Your registration completed"));
    driver.FindElement(By.CssSelector(".register-continue-button")).Click();
    driver.FindElement(By.LinkText("Log in")).Click();
    driver.FindElement(By.Id("Email")).Click();
    driver.FindElement(By.Id("Email")).SendKeys("test@mail.com");
    driver.FindElement(By.Id("Password")).SendKeys("test123");
    driver.FindElement(By.CssSelector(".login-button")).Click();
    driver.FindElement(By.LinkText("My account")).Click();
    driver.FindElement(By.CssSelector("h1")).Click();
    driver.FindElement(By.CssSelector("h1")).Click();
    Assert.That(driver.FindElement(By.CssSelector("h1")).Text, Is.EqualTo("My account - Customer info"));
    driver.FindElement(By.LinkText("Log out")).Click();
    driver.Close();
  }
}
