// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class Testnisluaj3Test {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void testnisluaj3() {
    driver.Navigate().GoToUrl("https://demo.nopcommerce.com/");
    driver.Manage().Window.Size = new System.Drawing.Size(1536, 824);
    driver.FindElement(By.LinkText("Electronics")).Click();
    driver.FindElement(By.CssSelector(".item-box:nth-child(2) img")).Click();
    driver.FindElement(By.Id("products-orderby")).Click();
    driver.FindElement(By.CssSelector(".item-box:nth-child(1) .prices")).Click();
    Assert.That(driver.FindElement(By.CssSelector(".item-box:nth-child(1) .prices")).Text, Is.EqualTo("$245.00"));
    driver.FindElement(By.CssSelector(".item-box:nth-child(2) .prices")).Click();
    Assert.That(driver.FindElement(By.CssSelector(".item-box:nth-child(2) .prices")).Text, Is.EqualTo("$100.00"));
    driver.FindElement(By.CssSelector(".item-box:nth-child(3) .prices")).Click();
    Assert.That(driver.FindElement(By.CssSelector(".item-box:nth-child(3) .prices")).Text, Is.EqualTo("$349.00"));
    driver.FindElement(By.CssSelector(".master-wrapper-page")).Click();
    driver.FindElement(By.Id("products-orderby")).Click();
    {
      var dropdown = driver.FindElement(By.Id("products-orderby"));
      dropdown.FindElement(By.XPath("//option[. = 'Name: A to Z']")).Click();
    }
    driver.FindElement(By.CssSelector(".item-box:nth-child(1) .details")).Click();
    Assert.That(driver.FindElement(By.CssSelector(".item-box:nth-child(1) .prices")).Text, Is.EqualTo("$245.00"));
    driver.FindElement(By.CssSelector(".item-box:nth-child(2) .details")).Click();
    Assert.That(driver.FindElement(By.CssSelector(".item-box:nth-child(2) .prices")).Text, Is.EqualTo("$100.00"));
    driver.FindElement(By.CssSelector(".item-box:nth-child(3) .prices")).Click();
    Assert.That(driver.FindElement(By.CssSelector(".item-box:nth-child(3) .prices")).Text, Is.EqualTo("$349.00"));
    driver.FindElement(By.CssSelector(".master-wrapper-page")).Click();
    driver.FindElement(By.Id("products-orderby")).Click();
    {
      var dropdown = driver.FindElement(By.Id("products-orderby"));
      dropdown.FindElement(By.XPath("//option[. = 'Price: Low to High']")).Click();
    }
    driver.FindElement(By.CssSelector(".item-box:nth-child(1) .prices")).Click();
    Assert.That(driver.FindElement(By.CssSelector(".item-box:nth-child(1) .prices")).Text, Is.EqualTo("$100.00"));
    driver.FindElement(By.CssSelector(".item-box:nth-child(2) .prices")).Click();
    Assert.That(driver.FindElement(By.CssSelector(".item-box:nth-child(2) .prices")).Text, Is.EqualTo("$245.00"));
    driver.FindElement(By.CssSelector(".item-box:nth-child(3) .prices")).Click();
    Assert.That(driver.FindElement(By.CssSelector(".item-box:nth-child(3) .prices")).Text, Is.EqualTo("$349.00"));
    driver.FindElement(By.CssSelector(".master-wrapper-page")).Click();
    driver.FindElement(By.Id("products-orderby")).Click();
    {
      var dropdown = driver.FindElement(By.Id("products-orderby"));
      dropdown.FindElement(By.XPath("//option[. = 'Position']")).Click();
    }
    driver.FindElement(By.CssSelector(".item-box:nth-child(1) .prices")).Click();
    Assert.That(driver.FindElement(By.CssSelector(".item-box:nth-child(1) .prices")).Text, Is.EqualTo("$245.00"));
    driver.FindElement(By.CssSelector(".item-box:nth-child(2) .prices")).Click();
    Assert.That(driver.FindElement(By.CssSelector(".item-box:nth-child(2) .prices")).Text, Is.EqualTo("$100.00"));
    driver.FindElement(By.CssSelector(".item-box:nth-child(3) .details")).Click();
    Assert.That(driver.FindElement(By.CssSelector(".item-box:nth-child(3) .prices")).Text, Is.EqualTo("$349.00"));
    driver.FindElement(By.Id("products-orderby")).Click();
    {
      var dropdown = driver.FindElement(By.Id("products-orderby"));
      dropdown.FindElement(By.XPath("//option[. = 'Price: Low to High']")).Click();
    }
    driver.FindElement(By.CssSelector(".item-box:nth-child(1) .prices")).Click();
    Assert.That(driver.FindElement(By.CssSelector(".item-box:nth-child(1) .prices")).Text, Is.EqualTo("$100.00 "));
    driver.FindElement(By.CssSelector(".item-box:nth-child(2) .details")).Click();
    Assert.That(driver.FindElement(By.CssSelector(".item-box:nth-child(2) .prices")).Text, Is.EqualTo("$245.00"));
    driver.FindElement(By.CssSelector(".item-box:nth-child(3) .prices")).Click();
    Assert.That(driver.FindElement(By.CssSelector(".item-box:nth-child(3) .prices")).Text, Is.EqualTo("$349.00"));
    driver.FindElement(By.CssSelector(".item-box:nth-child(3) .prices")).Click();
    driver.FindElement(By.CssSelector(".master-wrapper-page")).Click();
    driver.FindElement(By.Id("products-orderby")).Click();
    {
      var dropdown = driver.FindElement(By.Id("products-orderby"));
      dropdown.FindElement(By.XPath("//option[. = 'Name: A to Z']")).Click();
    }
    driver.FindElement(By.CssSelector(".item-box:nth-child(1) .prices")).Click();
    Assert.That(driver.FindElement(By.CssSelector(".item-box:nth-child(1) .prices")).Text, Is.EqualTo("$245.00"));
    driver.FindElement(By.CssSelector(".item-box:nth-child(2) .details")).Click();
    Assert.That(driver.FindElement(By.CssSelector(".item-box:nth-child(2) .prices")).Text, Is.EqualTo("$100.00"));
    driver.FindElement(By.CssSelector(".item-box:nth-child(2) .prices")).Click();
    Assert.That(driver.FindElement(By.CssSelector(".item-box:nth-child(3) .prices")).Text, Is.EqualTo("$349.00"));
    driver.FindElement(By.CssSelector(".master-wrapper-page")).Click();
    driver.FindElement(By.Id("products-orderby")).Click();
    {
      var dropdown = driver.FindElement(By.Id("products-orderby"));
      dropdown.FindElement(By.XPath("//option[. = 'Position']")).Click();
    }
    driver.FindElement(By.CssSelector(".item-box:nth-child(1) .prices")).Click();
    Assert.That(driver.FindElement(By.CssSelector(".item-box:nth-child(1) .prices")).Text, Is.EqualTo("$245.00"));
    driver.FindElement(By.CssSelector(".item-box:nth-child(2) .details")).Click();
    Assert.That(driver.FindElement(By.CssSelector(".item-box:nth-child(2) .prices")).Text, Is.EqualTo("$100.00"));
    driver.FindElement(By.CssSelector(".item-box:nth-child(3) .prices")).Click();
    Assert.That(driver.FindElement(By.CssSelector(".item-box:nth-child(3) .prices")).Text, Is.EqualTo("$349.00"));
    driver.Close();
  }
}
